version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pgad-postgres
    restart: always
    environment:
      POSTGRES_USER: pgad_user
      POSTGRES_PASSWORD: pgad_password
      POSTGRES_DB: pgad
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgad-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgad.com"
      PGADMIN_DEFAULT_PASSWORD: "pgad_admin"
    ports:
      - "8081:80"
    depends_on:
      - postgres
